import type { Template } from '../types';

export const sampleTemplate: Template = {
  id: 'sample-school-cr80',
  name: 'Modern School CR80',
  description: 'Front and back CR80 template for student ID cards.',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  canvasWidth: 1013,
  canvasHeight: 638,
  backgroundColor: '#f8fafc',
  columnMapping: {
    StudentID: 'StudentID',
    AdmissionNo: 'AdmissionNo',
    Name: 'Name',
    Class: 'Class',
    Section: 'Section',
    Department: 'Department',
    BloodGroup: 'BloodGroup',
    DOB: 'DOB',
    Phone: 'Phone',
    Address: 'Address',
  },
  frontElements: [
    {
      id: 'front-bg-band',
      type: 'shape',
      name: 'Header band',
      x: 0,
      y: 0,
      width: 1013,
      height: 164,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      shapeType: 'rect',
      backgroundColor: '#155e75',
      cornerRadius: 0,
    },
    {
      id: 'school-name',
      type: 'text',
      name: 'School name',
      x: 188,
      y: 38,
      width: 650,
      height: 54,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'GREEN VALLEY MATRIC SCHOOL',
      fontFamily: 'Noto Sans',
      fontSize: 36,
      fontWeight: '800',
      fill: '#ffffff',
      align: 'center',
    },
    {
      id: 'card-title',
      type: 'text',
      name: 'Card title',
      x: 342,
      y: 104,
      width: 330,
      height: 36,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'STUDENT ID CARD',
      fontFamily: 'Noto Sans',
      fontSize: 22,
      fontWeight: '700',
      fill: '#cffafe',
      align: 'center',
    },
    {
      id: 'student-photo',
      type: 'photo',
      name: 'Photo',
      x: 62,
      y: 210,
      width: 250,
      height: 300,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      cornerRadius: 24,
      borderWidth: 8,
      borderColor: '#ffffff',
    },
    {
      id: 'name',
      type: 'text',
      name: 'Name',
      x: 350,
      y: 212,
      width: 560,
      height: 56,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: '{{Name}}',
      fontFamily: 'Noto Sans',
      fontSize: 34,
      fontWeight: '800',
      fill: '#0f172a',
    },
    {
      id: 'class',
      type: 'text',
      name: 'Class',
      x: 352,
      y: 288,
      width: 470,
      height: 42,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'Class {{Class}} - {{Section}}',
      fontFamily: 'Noto Sans',
      fontSize: 26,
      fontWeight: '700',
      fill: '#164e63',
    },
    {
      id: 'id-line',
      type: 'text',
      name: 'Student ID',
      x: 352,
      y: 356,
      width: 410,
      height: 36,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'ID: {{StudentID}}   Adm: {{AdmissionNo}}',
      fontFamily: 'Noto Sans',
      fontSize: 22,
      fontWeight: '600',
      fill: '#334155',
    },
    {
      id: 'blood',
      type: 'text',
      name: 'Blood group',
      x: 352,
      y: 410,
      width: 300,
      height: 32,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'Blood: {{BloodGroup}}',
      fontFamily: 'Noto Sans',
      fontSize: 20,
      fontWeight: '700',
      fill: '#be123c',
    },
    {
      id: 'qr',
      type: 'qrcode',
      name: 'QR Code',
      x: 800,
      y: 412,
      width: 132,
      height: 132,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      qrDataType: 'json',
      dataField: 'StudentID',
    },
  ],
  backElements: [
    {
      id: 'back-header',
      type: 'shape',
      name: 'Back header',
      x: 0,
      y: 0,
      width: 1013,
      height: 96,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      shapeType: 'rect',
      backgroundColor: '#155e75',
    },
    {
      id: 'back-title',
      type: 'text',
      name: 'Back title',
      x: 46,
      y: 30,
      width: 920,
      height: 34,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'This card is the property of Green Valley Matric School',
      fontFamily: 'Noto Sans',
      fontSize: 24,
      fontWeight: '700',
      fill: '#ffffff',
      align: 'center',
    },
    {
      id: 'address',
      type: 'text',
      name: 'Address',
      x: 90,
      y: 148,
      width: 820,
      height: 96,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'Address: {{Address}}',
      fontFamily: 'Noto Sans',
      fontSize: 24,
      fontWeight: '600',
      fill: '#0f172a',
    },
    {
      id: 'phone',
      type: 'text',
      name: 'Phone',
      x: 90,
      y: 270,
      width: 520,
      height: 40,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'Phone: {{Phone}}',
      fontFamily: 'Noto Sans',
      fontSize: 24,
      fontWeight: '600',
      fill: '#334155',
    },
    {
      id: 'barcode',
      type: 'barcode',
      name: 'Barcode',
      x: 150,
      y: 398,
      width: 710,
      height: 118,
      rotation: 0,
      opacity: 1,
      locked: false,
      visible: true,
      dataField: 'StudentID',
      barcodeFormat: 'CODE128',
    },
  ],
};
